title: "JUPY-TEST"
copyright: '2024, Peak Solution'
author: 'NLA>'

execute:
  execute_notebooks: "force"

parse:
  myst_enable_extensions:
    - html_image
    - dollarmath

bibtex_bibfiles:
  - bibliography.bib

sphinx:
  config:
    bibtex_reference_style: author_year
